spring:
  datasource:
    url: jdbc:postgresql://postgres/ordersapi
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create